CC := /usr/bin/gcc
CFLAGS := -std=c17 -O3 -DNDEBUG -Wall -Wextra
JSON_CFLAGS := $(shell pkg-config --cflags json-c)
JSON_LIBS := $(shell pkg-config --libs json-c)
OPENSSL_PREFIX := /opt/homebrew/opt/openssl@3

.PHONY: all clean test

all: aa_render_c

aa_render_c: aa_render_c.c
	$(CC) $(CFLAGS) $(JSON_CFLAGS) $< -o $@ $(JSON_LIBS) -L$(OPENSSL_PREFIX)/lib -lcrypto -lm

test: aa_render_c
	./aa_render_c inventory "/Users/barbalet/next/github/next/fieldofchaos-chechnya/youtube video/aa/render_work"

clean:
	rm -f aa_render_c
